<a href="https://colab.research.google.com/github/janvimehta25/InspirationalQuotes/blob/main/QuoteRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import difflib 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
df = pd.read_excel(r'/content/Quotes1.xlsx')
print(df)

     Sr.no                                             Quotes  \
0        1  Though I may be been constructed," he said, "s...   
1        2  I'm afraid that the following syllogism may be...   
2        3  The question of whether a computer can think i...   
3        4  To deny humanity the lesson of consequences wo...   
4        5  I believe that at the end of the century the u...   
..     ...                                                ...   
116    117  Sometimes at night I worry about TAMMY. I worr...   
117    118  AI wont be fool proof in the future since it w...   
118    119  As data and science become more accessible and...   
119    120  The onboard computer just wants to say a few w...   
120    121  Though I may be been constructed," he said, "s...   

                       Authors                    Types  
0           C. Robert Cargill,  Artificial Intelligence  
1                  Alan Turing             Data Science  
2           Edsger W. Dijkstra  Artificial In

In [5]:
df.head()

Sr.no                                             Quotes  \
0      1  Though I may be been constructed," he said, "s...   
1      2  I'm afraid that the following syllogism may be...   
2      3  The question of whether a computer can think i...   
3      4  To deny humanity the lesson of consequences wo...   
4      5  I believe that at the end of the century the u...   

              Authors                    Types  
0  C. Robert Cargill,  Artificial Intelligence  
1         Alan Turing             Data Science  
2  Edsger W. Dijkstra  Artificial Intelligence  
3    Neal Shusterman,         Machine Learning  
4        Alan Turing,             Data Science

In [6]:
df['index'] = [i for i in range(0, len(df.values))]
print(df.head())

   Sr.no                                             Quotes  \
0      1  Though I may be been constructed," he said, "s...   
1      2  I'm afraid that the following syllogism may be...   
2      3  The question of whether a computer can think i...   
3      4  To deny humanity the lesson of consequences wo...   
4      5  I believe that at the end of the century the u...   

              Authors                    Types  index  
0  C. Robert Cargill,  Artificial Intelligence      0  
1         Alan Turing             Data Science      1  
2  Edsger W. Dijkstra  Artificial Intelligence      2  
3    Neal Shusterman,         Machine Learning      3  
4        Alan Turing,             Data Science      4  


In [7]:
selected_features = ['Sr.no', 'Authors', 'Quotes', 'Types']
print(selected_features)

['Sr.no', 'Authors', 'Quotes', 'Types']


In [8]:
for feature in selected_features :
  df[feature] = df[feature].fillna('')

In [9]:
vectorizer = TfidfVectorizer()

In [13]:
feature_vectors = vectorizer.fit_transform(selected_features)

In [14]:
print(feature_vectors)

  (0, 1)	0.7071067811865476
  (0, 3)	0.7071067811865476
  (1, 0)	1.0
  (2, 2)	1.0
  (3, 4)	1.0


In [15]:
similarity = cosine_similarity(feature_vectors)

In [16]:
print(similarity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
print(similarity.shape)

(4, 4)


In [27]:
df = input('Enter type of quote you wish to see')

Enter type of quote you wish to seeNLP


In [28]:
list_of_all_types = ['Artificial Intelligence', 'Data Science', 'NLP', 'Deep Learning']
print(list_of_all_types)

['Artificial Intelligence', 'Data Science', 'NLP', 'Deep Learning']


In [30]:
find_close_match = difflib.get_close_matches(df, list_of_all_types)
print(find_close_match)

['NLP']


In [31]:
close_match = find_close_match[0]
print(close_match)

NLP


In [ ]:
index_of_the_quote = df[df.Types == close_match]["index"].values[0]
print(index_of_the_quote)

In [ ]:
#similarity score
similarity_score = list(enumerate(similarity[index_of_the_quote]))
print(similarity_score)

In [ ]:
len(similarity_score)

In [ ]:
sorted_similar_types = sorted(similarity_score, key= lambda x:x[1], reverse=True)
print(sorted_similar_types)

In [ ]:
i=1 
for quotes in sorted_similar_types:
  index = quotes[0]
  Types_from_index = df[df.index==index]['Types'].values[0]
  if(i<60):
    print(i, '', Types_from_index)
    i+=1

In [ ]:
quote_name=input('Enter the type of quote you are seeking: ') 

list_of_all_profiles=df['profile'].tolist() 
 
find_close_match=difflib.get_close_matches(df,list_of_all_profiles) 
 
close_match=find_close_match[0] 
index_of_the_quote=df[df.types == close_match]["index"].values[0] 

similarity_score=list(enumerate(similarity[index_of_the_job])) 

sorted_similar_types= sorted(similarity_score,key= lambda x:x[1], reverse=True) 
 
print('Suggested quotes are as follows:\n') 
i=1 
for quotes in sorted_similar_types: 
  index=quotes[0] 
  types_from_index= df[df.index==index]['profile'].values[0] 
  if(i<60): 
    print(i,'',types_from_index) 
    i+=1 